update cqfd
Change-Id: Id87bad8824895a188a66d14babcbde0f4ef66fcd

diff --git a/cqfd b/cqfd
--- a/cqfd
+++ b/cqfd
@@ -21,10 +21,14 @@ set -e
 set -o pipefail
 
 PROGNAME=$(basename "$0")
-VERSION=5.8.0-dev
+VERSION=5.10.2
 cqfddir=".cqfd"
 cqfdrc=".cqfdrc"
 cqfd_user="${USER:-'builder'}"
+cqfd_user_uid="$(id -u)"
+cqfd_user_uid="${cqfd_user_uid:-1000}"
+cqfd_user_gid="$(id -g)"
+cqfd_user_gid="${cqfd_user_gid:-1000}"
 cqfd_user_home="${HOME:-'/home/builder'}"
 cqfd_user_cwd=${PWD:-"$cqfd_user_home/src"}
 cqfd_shell="${CQFD_SHELL:-/bin/bash}"
@@ -50,6 +54,8 @@ Options:
 Commands:
     init                 Initialize project build container.
     deinit               Deinitialize project build container.
+	images               List all cqfd container images.
+	prune                Remove all cqfd container images.
     exec cmd [args]      Run argument(s) inside build container.
     flavors              List flavors from config file to stdout.
     run [cmdstring]      Run argument(s) inside build container.
@@ -122,6 +128,36 @@ image_is_running() {
 	test "${#ids[@]}" -gt 0
 }
 
+## list_images() - list all docker images generated by cqfd
+list_images() {
+	local user
+	local image
+	local images
+
+	user=${USER//[^0-9a-zA-Z\-]/_}
+
+	mapfile -t images < <("$cqfd_docker" images "cqfd_$user\_*" --format "{{.Repository}}")
+
+	for image in "${images[@]}"; do
+		echo "$image"
+	done
+}
+
+## prune_images() - remove all docker images generated by cqfd
+prune_images() {
+	local images
+
+	mapfile -t images < <(list_images)
+
+	# Remove unused images if any
+	if [ "${#images[@]}" -gt 0 ]; then
+		warn "prune: found ${#images[@]} unused images to remove."
+		"$cqfd_docker" rmi -f "${images[@]}"
+	else
+		warn "prune: no unused images to remove"
+fi
+}
+
 ## docker_build() - initialize build container
 docker_build() {
 	local args=()
@@ -152,7 +188,7 @@ docker_build() {
 
 	# Set the context
 	if [ -z "$project_build_context" ]; then
-		args+=("$(dirname "$dockerfile")")
+		args+=("$(dirname "$dockerfile")" --file "$dockerfile")
 	else
 		args+=("$project_build_context" --file "$dockerfile")
 	fi
@@ -308,6 +344,12 @@ docker_run() {
 		done
 	fi
 
+	if [ "$cqfd_docker" = "podman" ]; then
+		args+=(--userns="keep-id")
+		args+=(--user=root)
+		args+=(--security-opt label=disable)
+	fi
+
 	# Set HOME variable for the $cqfd_user, except if it was explicitly set
 	# via CQFD_EXTRA_RUN_ARGS or docker_run_args
 	if ! echo "$CQFD_EXTRA_RUN_ARGS $build_docker_run_args" |
@@ -315,7 +357,7 @@ docker_run() {
 		args+=(--env "HOME=$cqfd_user_home")
 	fi
 
-	if [ "$CQFD_NO_USER_SSH_CONFIG" != true ]; then
+	if [ "$CQFD_NO_USER_SSH_CONFIG" != true ] && [ -d "$HOME/.ssh" ]; then
 		args+=(--volume "$HOME/.ssh:$cqfd_user_home/.ssh")
 	fi
 
@@ -332,7 +374,11 @@ docker_run() {
 		args+=(--mount "type=bind,src=$HOME/.gitconfig,dst=$cqfd_user_home/.gitconfig")
 	fi
 
-	if [ "$CQFD_BIND_DOCKER_SOCK" = true ]; then
+	if [ "$CQFD_NO_SYSTEM_GIT_CONFIG" != true ] && [ -f "/etc/gitconfig" ]; then
+		args+=(--mount "type=bind,src=/etc/gitconfig,dst=/etc/gitconfig")
+	fi
+
+	if [ "$CQFD_BIND_DOCKER_SOCK" = true ] || [ "$build_bind_docker_sock" = true ]; then
 		args+=(--volume /var/run/docker.sock:/var/run/docker.sock)
 	fi
 
@@ -428,16 +474,17 @@ make_archive() {
 	# also replace variable names - beware with eval
 	eval "release_archive=$release_archive"
 
-	# setting tar_transform=yes will move files to the root of a tar archive
-	if [ "$release_transform" = "yes" ]; then
+	# setting tar_transform=yes or tar_transform=true will move files to the
+	# root of a tar archive
+	if [ "$release_tar_transform" = "yes" ] || [ "$release_tar_transform" = "true" ]; then
 		tar_opts+=('--transform' 's/.*\///g')
 	fi
 
 	# setting tar_options=x will pass the options to tar
-	if [ "$release_tar_opts" ]; then
+	if [ "$release_tar_options" ]; then
 		local array
 		# shellcheck disable=SC2162
-		read -a array <<<"$release_tar_opts"
+		read -a array <<<"$release_tar_options"
 		tar_opts+=("${array[@]}")
 	fi
 
@@ -513,11 +560,19 @@ if ! shell=\$(command -v "$cqfd_shell"); then
 	exit 127
 fi
 
+# Delete $cqfd_user_uid user if it exists
+conflicting_users="\$(awk -F: '\$3 == $cqfd_user_uid {printf ("%s ", \$1)}' /etc/passwd)"
+if [ -n "\$conflicting_users" ]; then
+	for u in \$conflicting_users; do
+		userdel "\$u"
+	done
+fi
+
 # Add the host's user and group to the container, and adjust ownership
-groupadd -og "${GROUPS[0]}" -f builders
-useradd -s "\$shell" -oN -u "$UID" -g "${GROUPS[0]}" -d "$cqfd_user_home" "$cqfd_user"
+groupadd -og "$cqfd_user_gid" -f builders
+useradd -s "\$shell" -oN -u "$cqfd_user_uid" -g "$cqfd_user_gid" -d "$cqfd_user_home" "$cqfd_user"
 mkdir -p "$cqfd_user_home"
-chown "$UID:${GROUPS[0]}" "$cqfd_user_home"
+chown "$cqfd_user_uid:$cqfd_user_gid" "$cqfd_user_home"
 
 # Add specified groups to cqfd_user
 for g in ${CQFD_GROUPS[*]}; do
@@ -667,15 +722,17 @@ load_config() {
 	# shellcheck disable=SC2154
 	build_user_extra_groups="$user_extra_groups"
 	# shellcheck disable=SC2154
+	build_bind_docker_sock="$bind_docker_sock"
+	# shellcheck disable=SC2154
 	release_files="$files"
 	# shellcheck disable=SC2154
 	release_archive="$archive"
 	# shellcheck disable=SC2154
-	release_transform="$tar_transform"
+	release_tar_transform="$tar_transform"
 	# shellcheck disable=SC2154
-	release_tar_opts="$tar_options"
+	release_tar_options="$tar_options"
 
-	dockerfile="$cqfddir/${build_distro:-docker}/Dockerfile"
+	dockerfile=$(realpath "$cqfddir/${build_distro:-docker}/Dockerfile")
 	if [ ! -f "$dockerfile" ]; then
 		die "$dockerfile not found"
 	fi
@@ -687,8 +744,7 @@ load_config() {
 		local dockerfile_hash
 
 		# This will look like cqfd_USER_ORG_NAME_HASH
-		# shellcheck disable=SC2001
-		format_user=$(sed 's/[^0-9a-zA-Z\-]/_/g' <<<"$USER")
+		format_user=${USER//[^0-9a-zA-Z\-]/_}
 		dockerfile_hash=$(sha256sum "$dockerfile" | cut -b 1-7)
 		docker_img_name="cqfd${format_user:+_$format_user}_${project_org}_${project_name}_${dockerfile_hash}${build_distro:+_$build_distro}"
 	fi
@@ -702,14 +758,14 @@ set_shell_histfile() {
 
 	case "$program_basename" in
 	bash|zsh)
-		shell_histfile="${HISTFILE:-$HOME/.${program_basename}_history}"
+		shell_histfile="${CQFD_HISTFILE:-$HOME/.${program_basename}_history}"
 		;;
 	ksh)
-		shell_histfile="${HISTFILE:-$HOME/.sh_history}"
+		shell_histfile="${CQFD_HISTFILE:-$HOME/.sh_history}"
 		;;
 	tcsh)
 		# Note: tcsh history does not persist without doing `history -S` on exit
-		shell_histfile="${HISTFILE:-$HOME/.history}"
+		shell_histfile="${CQFD_HISTFILE:-$HOME/.history}"
 		;;
 	*)
 		shell_histfile=""
@@ -760,6 +816,14 @@ while [ $# -gt 0 ]; do
 		docker_rmi
 		exit
 		;;
+	images)
+		list_images
+		exit
+		;;
+	prune)
+		prune_images
+		exit
+		;;
 	flavors)
 		load_config
 		echo "$build_flavors"
@@ -806,6 +870,7 @@ while [ $# -gt 0 ]; do
 			has_to_release=true
 		fi
 
+		cqfd_command="$1"
 		shift
 
 		# No more args? run default command
@@ -817,14 +882,37 @@ while [ $# -gt 0 ]; do
 
 			if [ "$#" -lt 1 ]; then
 				usage
-				die "run -c: Missing arguments!"
+				die "$cqfd_command -c: Missing arguments!"
 			fi
 			break
 		fi
 
+		# set HISTFILE if using `cqfd run bash`
 		set_shell_histfile "$1"
 		# Run alternate command
 		has_alternate_command=true
+
+		# Display a warning message if using run with at least one quoted argument
+		show_error_message=false
+		if [ "$#" -gt 1 ]; then
+			# Rebuild the initial command with quotes only for arguments containing spaces
+			initial_command=""
+			for arg in "$@"; do
+				if [[ $arg = *" "* ]]; then
+					initial_command+="'$arg' "
+					show_error_message=true
+				else
+					initial_command+="$arg "
+				fi
+			done
+			initial_command=${initial_command%?}
+			if "$show_error_message"; then
+				warn "command '$cqfd_command' with multiple arguments is ambiguous," \
+					"please consider the commands 'exec' or 'shell' instead:"
+				echo "               cqfd exec $initial_command" >&2
+				echo "               cqfd shell -c \"$initial_command\"" >&2
+			fi
+		fi
 		break
 		;;
 	sh|ash|dash|bash|ksh|zsh|csh|tcsh|fish|shell)
